module.exports = [{
    ignores: ["dist/**/*.js", "typechain/**/*.js", "index.js"], // generated files
    languageOptions: {
        sourceType: "commonjs",
    },
    "rules": {
        ...require("@eslint/js").configs.recommended.rules,
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1,
                "flatTernaryExpressions": true
            },
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "warn",
            "never"
        ],
        "no-console": "error",
        "keyword-spacing": "error",
        "func-call-spacing": "error",
        "space-infix-ops": "error",
        "space-before-blocks": "error",
        "no-unexpected-multiline": "error"
    }
}, {
    files: ["test/**/*.js"],
    languageOptions: {
        globals: { // mocha
            describe: "readonly",
            it: "readonly",
            before: "readonly",
            beforeEach: "readonly",
            after: "readonly",
            afterEach: "readonly",
        },
    },
    rules: {
        "no-console": "warn",
    },
}, {
    files: ["scripts/**/*.js", "hardhat.config.js"],
    languageOptions: {
        globals: {
            process: "readonly",
            console: "readonly",
        }
    },
    rules: {
        "no-console": "off",
    },
}, {
    files: ["*.js"],
    rules: {
        "semi": "off", // autogenerated files
    },
}]
